In [1]:
#data 
from pycaret.datasets import get_data
dataset = get_data('iris')
dataset

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [2]:
#check the shape of data
dataset.shape

(150, 5)

In [3]:
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (135, 5)
Unseen Data For Predictions: (15, 5)

In [4]:
#setting up the environment in Pycaret
from pycaret.classification import *
exp_mclf101 = setup(data = data, target = 'species', session_id=123)

In [5]:
best = compare_models()

In [ ]:
dt = create_model('dt')

In [ ]:
#trained model object is stored in the variable 'dt'. 
print(dt)

In [ ]:
#model 2
knn = create_model('knn')

In [ ]:
#model 3 logistic regresion
lr = create_model('lr')

In [ ]:
tuned_lr = tune_model(lr)

In [ ]:
tuned_dt = tune_model(dt)

In [ ]:
#tuned model object is stored in the variable 'tuned_dt'. 
print(tuned_dt)

In [ ]:
import numpy as np
tuned_knn = tune_model(knn, custom_grid = {'n_neighbors' : np.arange(0,50,1)})

In [ ]:
plot_model(tuned_knn, plot = 'confusion_matrix')

In [ ]:
plot_model(tuned_knn, plot = 'class_report')

In [ ]:
plot_model(tuned_knn, plot='boundary')

In [ ]:
plot_model(tuned_knn, plot = 'error')

In [ ]:
evaluate_model(tuned_knn)

In [ ]:
#prediction/tests
predict_model(tuned_knn);

In [ ]:
#The accuracy on the test/hold-out set is 0.9512 compared to 0.9356 achieved on 
#the tuned_knn CV results (in section 9.2 above). This is not a significant difference. 
#If there is a large variation between the test/hold-out and CV results, 
#then this would normally indicate over-fitting but could also be due to several other factors 
#and would require further investigation. In this case, we will move forward with finalizing 
#the model and predicting on unseen data (the 10% that we had separated in the beginning and
#never exposed to PyCaret).

In [ ]:
#(TIP : It's always good to look at the standard deviation of CV results when using create_model()

In [ ]:
#final model for deployment
final_knn = finalize_model(tuned_knn)

In [ ]:
#Final K Nearest Neighbour parameters for deployment
print(final_knn)

In [ ]:
#predict unseen data
unseen_predictions = predict_model(final_knn, data=data_unseen)
unseen_predictions.head()

In [ ]:
#saving the model
save_model(final_knn,'Final KNN Model 08Feb2020')

In [ ]:
#loading saved model
saved_final_knn = load_model('Final KNN Model 08Feb2020')

In [ ]:
new_prediction = predict_model(saved_final_knn, data=data_unseen)

In [ ]:
new_prediction.head()